let
    ErrorBase = SafeguardPasswords.ImportModule("CommonErrorBase.pqm"),
    CommonRequestErrors.ErrorMap = SafeguardPasswords.ImportFunction("ErrorMap", "CommonRequestErrors.pqm"),
    RequestErrors.ErrorMap = CommonRequestErrors.ErrorMap

in
    [
        ErrorCodes = List.Transform(Record.FieldNames(RequestErrors.ErrorMap), each Number.FromText(_)),
        ErrorMap = RequestErrors.ErrorMap
    ]
